# Site settings
title: Kris Hatcher
name: Kris Hatcher

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: GitHub
   url: https://github.com/krishatcher
 - title: StackOverflow
   url: https://stackoverflow.com/users/4603690/kris-hatcher
 - title: LinkedIn
   url: https://www.linkedin.com/in/krishatcher/

#Any buzzword skills you want to include
skills:
 - Angular
 - React
 - Golang
 - C# .NET
 - PHP
 - REST
 - GraphQL
 - PostgreSQL
 - SQL
 - Terraform
 - Docker
 - Kubernetes
 - AWS
 - Tech Architecture

#Work experience is required
roles:
 - title: Technical Team Lead & Senior Engineer
   start: Aug 2021
   end: Ongoing
   employer: 2U, LLC
   description: As a technical lead, I provided architectural and technical guidance to a team of nine, fostering collaboration and ensuring project alignment with organizational goals. I facilitated Scrum ceremonies using Atlassian tools like Jira and Confluence to enhance team efficiency and project transparency. Monitoring deployed applications and coordinating after-hours support when necessary were integral aspects of my role. Notably, I implemented a ChatGPT-based AI chatbot with a custom knowledge base to address student inquiries in an online learning environment. Additionally, I spearheaded the integration of a third-party toolset through a GraphQL-based process. My work encompassed the development and maintenance of five distinct applications using Golang and React, hosted on AWS, managed via Terraform, and deployed through Buildkite. My technical expertise spans AWS, Terraform, PostgreSQL, Golang, React, Docker, and Kubernetes, allowing me to deliver scalable, reliable, and innovative solutions.
 - title: Team Lead & ScrumMaster
   start: May 2015
   end: Aug 2021
   employer: Smart Data Systems, LLC
   description: Worked with client companies to supplement existing development workforces and deliver net-new or major change functionality in a way which was indistinguishable from software developed by existing workforce. Assisted both with software development and implementation of agile methodologies in client environments. Clients existed across a variety of verticals such as Healthcare, Health Insurance, Construction Management, and Healthcare Management. Led teams from 3 to 25 people. Managed AWS infrasturcture, including budgeting for some clients. My technical skill set encompasses AWS, MS SQL, C# .NET, React, Angular, PHP, and TeamCity, enabling me to deliver scalable and client-focused solutions.
 - title: Web Development Supervisor
   start: Jan 2011
   end: Apr 2015
   employer: The Reynolds and Reynolds Company
   description: I provided guidance and leadership to a team of five developers, supporting their growth while maintaining focus on my own assigned tasks. I collaborated with associates to ensure their responsibilities were effectively managed and worked closely with other developers and teams to create web-based products that enhanced client productivity. My work involved leveraging tools and technologies such as MS SQL, C# .NET, jQuery, JavaScript, and TeamCity to deliver efficient and impactful solutions.

#Education is required
education:
 - level: Bachelor of Science (B.Sc.)
   date: Currently In Progress
   subject: Software Engineering
   school: Allegheny College
 - level: Certified ScrumMaster (CSM)
   date: 2016
   subject: Team Operations
   school: ScrumAlliance
 - level: Certified LeSS Practitioner
   date: 2019
   subject: Large Scale Scrum
   school: The LeSS Company B.V.
 - level: AWS Certified Solution Architect - Associate
   date: 2017
   subject: Cloud Utilization & Management
   school: Amazon Web Services

#List of interesting Github repo/projects to include - optional
#github:
# - krishatcher/SendContacts
# - krishatcher/wpCertifications
# - krishatcher/arduino-ColorOrgan

#Stackoverflow flair is optional
stackoverflow:
   profileurl: https://stackoverflow.com/users/4603690/kris-hatcher
   flairimageurl: https://stackoverflow.com/users/flair/4603690.png

#An additional info freetext section is optional at the bottom of the page - can be text or HTML
additionalinfo: |
   <strong>JVM</strong>: I am experienced in a variety of Java API’s and frameworks. I have recently worked with Spring 4, Spring Boot, JPA (Hibernate and EclipseLink) in addition to others.  In my current role Groovy is the primary language used - and I am familiar with many of the languages features and quirks (including writing <a target='_blank' href="https://dzone.com/articles/functional-programming-groovy">Functional Programming style groovy</a>). <br/><br/>
   <strong>Web Development</strong>: My server side web development experience has largely been based on the Spring MVC framework (although current role uses ColdFusion for server side web stack). I have also worked with some client side technology, having used jQuery, Bootstrap, LESS, SASS and have also experimented with other interesting technologies such as Backbone/Underscore/Require.<br/><br/>
   <strong>Development Control</strong>: I have a good knowledge of application life-cycle management and have worked with SVN, Git, Maven, Gradle, Sonar and Jenkins. I have experience with an array of testing tools and technologies.<br/><br/>
   I have also gained experience and knowledge of other technologies from several side projects and research that I have undertaken in my free time, including Android, a variety of social APIs (Twitter etc) and cloud platforms such as CloudFoundry/OpenShift/AppFog/Parse. <br/><br/>
   As part of Nerdability, I created, and am now primary contributor to, two Spring projects - <a target='_blank' href="https://github.com/robhinds/spring-social-geeklist">Spring-Social-Geeklist</a> and <a target='_blank' href="https://github.com/nerdability/spring-social-khan-academy">Spring-Social-Khan-Academy</a>, which provide core integration with those third-party APIs on top of the Spring Social framework. They are both listed as community projects: <a target='_blank' href="http://projects.spring.io/spring-social/">http://projects.spring.io/spring-social/</a>. <br/><br/>
   I write a blog covering technical and opinion articles that can be found here: <a target='_blank' href="http://automateddeveloper.blogspot.com/">automateddeveloper.blogspot.com</a> (I am also a <a target='_blank' href="https://dzone.com/users/899489/rhinds.html">DZone MVB</a>)
